### PR TITLE
FEATURE/MEDIUM: add support for additional http-check directives

### PR DESCRIPTION
**Pull request by anitgandhi**

### CODE REVIEW

**Comment by oktalz** [comment]
agreed, until 2.2 comes out, there might be additional changes, so lets wait a bit for this.
just a note:
this would also be a breaking change for config parser since this would change `HTTPCheck` struct

**Comment by anitgandhi** [comment]
Ah that's a good point about the breaking change. I will fix that by duplicating the fields and marking the old ones deprecated with a note that the inside the inner `Expect` struct should be used instead.

**Comment by anitgandhi** [comment]
Update: I've added back support for the old fields in a way that maintains compatibility, so this should no longer be a breaking change 👍

**Comment by anitgandhi** [comment]
I've updated `http-check send` and `http-check expect` for HAProxy 2.2-dev10 (mostly just supporting `uri-lf` and `body-lf` on the former. 

Also added a separate commit for `http-check connect`.

**Comment by anitgandhi** [comment]
@oktalz when you have some time, could I get a preliminary review of this? 2.2 is right around the corner :) 

I think I have all the fields covered as of 2.2-dev12 released a couple days ago, but I will of course confirm once 2.2 final is released.

**Comment by oktalz** [comment]
hi @anitgandhi 
sorry for a bit late response, i will take a look at it thoroughly tommorow

I having some doubts with including `LoopExpect` label since this looks a bit hackish
and also don't really like how we have `if c.Type == "expect" {` and similar in code

maybe something similar as for [http-request](https://github.com/haproxytech/config-parser/blob/master/parsers/http/http-request.go) parser would be more readable -> having 'actions' or sub-parsers as you may see it.

As i said tomorrow i will do a more in depth review of this PR

**Comment by oktalz** [comment]
@anitgandhi Do you plan to use this only as config-parser feature or do you plan/wish to use this with 
client-native and dataplaneapi also ?

If this is only for config-parser i can merge it today, but
after a discussion with colleagues, we decided that this change we will be treated differently in client-native and dataplaneapi.

config-parser is not tied to other projects so we can do a 3.0 version for this (then breaking) change sooner, when we have this new version of parser.

But I prefer it to be done in similar way as was done with http-request parser.
That way we have more cleaner state what is going on.
having many `if Type == "...." {`` is not something we desire much in this case.

**Comment by anitgandhi** [comment]
@oktalz Thanks for the initial review. Our intention is to use it only for config-parser at the moment, but this is not blocking us, so it's not required for us to have it merged today 🙂 

I think the `http-request` parser analog idea makes sense, I will work on that and update this PR accordingly 👍

**Comment by anitgandhi** [comment]
Hi @oktalz 👋 

I have a working re-implementation (not yet final) of this using HTTP actions here: https://github.com/haproxytech/config-parser/compare/master...digitalocean:http-check-v2

I am not opening a PR for it because I wanted to discuss a concern first: **this re-implementation would not be backwards compatible**. Since it's a new parser that must be registered with the same name, the current one (`types.HTTPCheck`) would have to go away. This implies having to create a v3, which I believe we were hoping to avoid, since dataplaneapi/client-native both rely on config-parser (based on their `go.mod` files). 

Perhaps you might know some way that we can allow double registration? In my testing, it failed because the data types won't match. I considered making a 3rd "meta-parser" type that would encompass the old and new, and figure out which one to delegate to; but the problem would remain - it would be a breaking change since `types.HTTPCheck` would not be useable anymore. 

If not, perhaps we can revisit the implementation in this PR with some cleanup (not using the loop label, breaking out into readable helper functions, etc), since it remains backwards compatible. 

Let me know your thoughts; thanks!

**Comment by oktalz** [comment]
hi @anitgandhi  double registration would complicate things a-lot, and other solutions i had  are also equally bad :)

lets just raise version to `v3`

config-parser is a library, yes, maybe its not ideal to raise version so soon, 
but on the other hand it is good PR, a good change and we all will benefit from it.

config-parser is not linked hard to dataplaneapi/client-native/specification
and we can use v3 parser in v2 dataplane.

also, loop label is OK-ish, we do not need to complicate just to complicate.

i will create v2 branch and maintain it for a while, so we don't force everybody to use new version.

**Comment by anitgandhi** [comment]
Ok that sounds good! I'll go ahead and open the PR then. 

Re: loop label, makes sense/agreed 👍 I tried to find a good way around it, like breaking it out into a function which would be the typical way to not have to use a loop label, but I think for this specific use case where we need `i`, this is the best way.

**Comment by anitgandhi** [comment]
Just wanted to point out one idea for the future (and perhaps it makes sense to tackle as part of v3) - it might be nice if `section-parsers.go` used a `map[string]ParserInterface` (map of parser name to `ParserInterface`). 

Doing so would allow overriding the registration of any given parser which would help a bit in the double registration issue, along with allowing users to create custom type replacements themselves and use their implementation, if desired.

**Comment by oktalz** [comment]
> Just wanted to point out one idea for the future (and perhaps it makes sense to tackle as part of v3) - it might be nice if `section-parsers.go` used a `map[string]ParserInterface`

parsers in map instead of list will change soon, its already being worked on. Main reason is actually seek performance that will be much faster then. We still need to have particular order for parsing and correctly writing them to file, 
so we need to mix few things here and there,
but that might also help in similar examples

**Comment by anitgandhi** [comment]
Oh right, good point about the ordering, I forgot about that. Great to hear it's being worked on though 👍👍

**Pull request closed without merging**
