### PR TITLE
FEATURE/MINOR: listen: add parsers

### PR DESCRIPTION
**Pull request by snorwin**
Add specific parsers for the `listen` section.

Signed-off-by: Norwin Schnyder norwin.schnyder+github@gmail.com

### CODE REVIEW

**Comment by oktalz** [comment]
Hi @snorwin , we need a bit better explanation of how message need to look :)

just change it to `MINOR: lis....`  


FEATURE is acctually in a debate should we allow it or not :)

**Comment by oktalz** [comment]
Hi @snorwin , we need a bit better explanation of how message need to look :)

just change it to `MINOR: lis....`  


FEATURE is acctually in a debate should we allow it or not :)

**Comment by oktalz** [comment]
we are leaving the listen section empty deliberatly, since its basically replaced with frontend/backend sections

but saying that, we could have a new [options](https://github.com/haproxytech/config-parser/tree/master/options) flag to allow parsers to be there.


option like `UseListenSectionParsers` that is **OFF** by default, but you could use to activate them.


would solution like that work for you ?


i can add option flag after we merge this (or you culd add it), it is relatevly simple to add it

**Comment by oktalz** [comment]
we are leaving the listen section empty deliberatly, since its basically replaced with frontend/backend sections

but saying that, we could have a new [options](https://github.com/haproxytech/config-parser/tree/master/options) flag to allow parsers to be there.


option like `UseListenSectionParsers` that is **OFF** by default, but you could use to activate them.


would solution like that work for you ?


i can add option flag after we merge this (or you culd add it), it is relatevly simple to add it

**Comment by snorwin** [comment]
Thanks for the feedback, I updated the commit name and added an option flag. It actually prevents the unintentional reordering of statements in the listen sections and makes the change backward compatible.

**Comment by oktalz** [comment]
thx @snorwin  !

**Pull request merged**
