### PR TITLE
FEATURE/MEDIUM: add support for additional http-check directives introduced in HAProxy 2.2

### PR DESCRIPTION
**Pull request by anitgandhi**
This is a re-open and re-implementation of #27 

It follows the HTTP Actions pattern to break out parsing implementations into "sub parsers". Because this replaces the prior existing implementation, it is a breaking change, and warrants a v3 release. 

See discussion in #27 .

### CODE REVIEW

**Comment by oktalz** [comment]
I will try to review this fully this week.
One thing i noticed is `This is a re-implementation of #27 to use ...` in commit message

Our policy is to not mention issues in commit messages via `#27` , but to do the opposite, in issue/PR we mention commit.
Reason for this is forking/cloning this project to other git servers where this link is incorrect or misleading. 
(you, for instance fork this to local Gitlab and have separate set of issues and MRs there and this link number 27 can be something totally unrelated)

**Comment by anitgandhi** [comment]
Gotcha; is it alright if I leave that message in the PR description so it's still linked in GitHub. I will remove it from the commit message.

**Comment by oktalz** [comment]
yes sure, 
only actual commit message is what I was talking about.  

PR is parft of github infrastructure and will always be linked to github and this particular repository, so there is no issues.

**Comment by anitgandhi** [comment]
Removed the link from the commit 👍

**Comment by anitgandhi** [comment]
👋 Hey @oktalz , just a friendly ping for review in case it was forgotten. Thanks in advance!

**Comment by oktalz** [comment]
Hi @anitgandhi, 
it wasn't forgotten, sorry for not replying faster :)

you can expect this to be merged next Monday (14th)

**Comment by anitgandhi** [comment]
Sounds good, thanks!

Any review/feedback I can incorporate before then?

**Comment by oktalz** [comment]
no seems good, thx, 
its just that some recent changes on internal structure of parsers was added, so i need to rebase this (and add one thing).

No need to worry about that, I'll will do what is needed.

To explain
```
preComments []string
``` 
was added/expected in every parser to catch comments that then stay with specific parser

for example
```
frontend http 
  mode http
  # some comment about why bind is on 0.0.0.0
  bind 0.0.0.0:80 name bind_1  
  default_backend default_backend
```

comment `# some comment about why bind is on 0.0.0.0` will stay in front of bind line
same goes for comments in front of sections etc.

this does not break behavior in general, but since all parsers needs to have this, 
if we just merge this as it is it won't build.
i will amend that to your commit (thx for PR, i don't need to put pressure on you of syncing this with master, for me its a simple change)

**Comment by anitgandhi** [comment]
Ah right. I already added it to the main new http-check parser, just not to each "sub-parser" (http action). I didn't see the other http actions having the `preComments` so I didn't include them there.

**Comment by oktalz** [comment]
actually, no rebasing or changes are needed

**Comment by oktalz** [comment]
I have merged this and also raised version to v3 so you can use it normally, 
we will still maintain v2 for quite a while, especially since we use that version in dataplane and k8s ingress controller.

**Pull request merged**
